### ISSUE TITLE
Async JS form submits?

### ISSUE THREAD

**Issue by ateesdalejr** [ateesdalejr/maildiscuss#6]
Is this a good idea? What if the client doesn't support ajax? Also what is our stance on using jQuery? Are you for or against it? Personally I'd rather just use vanilla js.

**Comment by csf30816** [comment]
jQuery is simpler to use but will increase bandwidth or loading time. Vanilla JS will work. We can use `<noscript>` to tell users to enable JS.

**Comment by ateesdalejr** [comment]
@csf30816 If you look at the current website I've got a broken implmentation. If you could fix it that would be nice. 👍

**Comment by csf30816** [comment]
ok, but first i ned to turn off sticky keys lol

**Comment by csf30816** [comment]
Well, you should have all JS in `/login` it should read when the submit button is clicked and send data to the API, that's what I meant. Is this what you want to accomplish?

**Comment by ateesdalejr** [comment]
@csf30816 apologies I forgot to push my changes. f55632758c04687c4fd6b257f9b745a056f392aa should contain all of the broken code.

**Comment by csf30816** [comment]
Oh OK lol I will check it now :)

**Comment by csf30816** [comment]
Ah I see, you still have the `action` attribute set on the form...

**Comment by amazinigmech2418** [comment]
So what is this issue about?

**Comment by csf30816** [comment]
I think it is fixed

**Comment by amazinigmech2418** [comment]
OK. It was mentioned in #7 so I thought it still needed to be fixed.

**Comment by csf30816** [comment]
We haven't launched to the FTP so it might still be broke.

**Comment by ateesdalejr** [comment]
@csf30816 It's still broken. :/
Says there was a problem with the request.

**Comment by ateesdalejr** [comment]
Do we really need asynchronous js? Most browsers handle a redirect pretty well because they already have the page in the cache.

**Comment by amazinigmech2418** [comment]
We should probably use asynchronous JS for the form submitting since that would allow for a wait system before the program finishes loading and errors.

**Comment by amazinigmech2418** [comment]
Also, I like jQuery. I think it would be useful.

**Comment by ateesdalejr** [comment]
Eh ok we can go with jQuery for now but I really don't like the extra KBs it adds to your page loads.

**Comment by amazinigmech2418** [comment]
I know I misspelled my username. XD If you want, we don't have to use jQuery for everything, but can use it for some advanced API. Not post since plain ajax is best for posting, but jQuery is great for get.
